title = "📯 Vrije Geluiden"
baseURL = "https://constantlam.github.io"
languageCode = "nl-nl"
theme = "ananke"
#themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "nl"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
# Articles are paginated with only three posts here for example. You can set the number of entries to show on this page with the "pagination" setting in the config file.
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/leeuw.jpg"
  recent_posts_number = 2
