---
date: 2020-01-03T11:13:32-04:00
description: "Wonderboom"
featured_image: ""
tags: ["planten"]
title: "Wonderboom"
---

bron: link:https://nl.wikipedia.org/wiki/Wonderboom[Wikipedia]

De wonderboom of wonderolieboom (Ricinus communis) is een snelgroeiende tropische plant, die buiten de tropen kruidachtig is.

In de tropen kan de plant na enkele jaren een hoogte tot 13 meter bereiken en heeft dan een verhoute stengel die op een stam lijkt. De vrucht wordt wonderboon genoemd hoewel de plant niet tot de vlinderbloemenfamilie behoort (zoals de gewone boon) maar tot de wolfsmelkfamilie (Euphorbiaceae). Uit wonderbonen wordt wonderolie geperst. De overblijvende pulp wordt wel als veevoeder gebruikt maar bevat het zeer sterke gif ricine dat eerst door een langdurige hittebehandeling onschadelijk moet worden gemaakt. Uit de overgebleven resten worden ook wel meststoffen gemaakt die in biologische teeltwijzen gebruikt worden.

Wonderbonen zijn erg giftig. Voor kinderen kan de consumptie van vijf à zes zaden al dodelijk zijn terwijl de dodelijke dosis voor volwassenen 15 à 20 bonen is.

De naam Ricinus is het Latijnse woord voor teek; dit waarschijnlijk omdat de bonen een patroon hebben en aan een kant een bobbeltje vertonen waardoor zij op bepaalde teken lijken. Het is onbekende waarom in de middeleeuwen Ricinus communis de naam christuspalm (Palma Christi) heeft gekregen.

De plant stamt waarschijnlijk uit Oost-Afrika en is tegenwoordig wereldwijd verspreid. De plant is vaak te vinden op braakliggend terrein en in de buurt van spoorwegen. Hij wordt ook vaak decoratief toegepast in parken.

De wonderboon is de enige soort in het geslacht Ricinus. Er is een grote morfologische variatie: naast kleine planten komen ook dwergtypen voor die als eenjarige plant worden gekweekt. Verder is er een enorme verscheidenheid in bladvorm en -kleur wat tot de teelt als sierplant heeft bijgedragen.

== Teelt en toepassingen

De wereldwijde productie van wonderbonen ligt op ongeveer 1 miljoen ton per jaar. De belangrijkste producenten bevinden zich in India, China, Brazilië en de voormalige Sovjet-Unie. Er zijn ook een aantal actieve kweekprogramma's.

Wonderolie, of castorolie, wordt al heel lang door de mens gebruikt. Wonderbonen zijn aangetroffen in Egyptische tomben uit 4000 v.Chr. en het gebruik van wonderolie, onder andere als lampolie, werd beschreven door Griekse reizigers, onder wie Herodotos.

In India is de olie al minstens sinds 2000 v.Chr. in gebruik als lampolie en laxeermiddel en ook in China wordt zij al eeuwen gebruikt, voornamelijk medicinaal.

Een modern voorbeeld van gebruik van olie van de wonderboom is een door DSM gemaakte bioplasticsoort met olie uit de wonderboom.

== Trivia

In het Bijbelboek Jona wordt beschreven dat een wonderboom in een dag opgroeit, tot vreugde van Jona, en daarna weer verwelkt. Deze plant groeide door een wonder van God, maar het is toeval dat de plant in het Nederlands 'wonderboom' heet.

